apiVersion: v1
kind: Service
metadata:
  name: image-classification-service
  labels:
    app: image-classification
spec:
  selector:
    app: image-classification
  ports:
    - name: inference
      port: 5544
      targetPort: 5544
    - name: monitoring
      port: 6100
  clusterIP: 10.101.156.113
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification
  labels:
    app: image-classification
spec:
  selector:
    matchLabels:
      app: image-classification
  replicas: 2
  template:
    metadata:
      labels:
        app: image-classification
    spec:
      containers:
        - name: image-classification
          image: image_classification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: inference
              containerPort: 5544
            - name: monitoring
              containerPort: 6100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-classification-monitor
  labels:
    app: image-classification
spec:
  selector:
    matchLabels:
      app: image-classification
  endpoints:
    - interval: 5s
      port: monitoring
