apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-p3dn
  version: "1.23"
  region: us-east-1
  tags:
    karpenter.sh/discovery: eks-p3dn

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

managedNodeGroups:

  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
 
  - name: p3dn
    instanceType: p3dn.24xlarge
    instancePrefix: p3dn
    privateNetworking: true
    availabilityZones: ["us-east-1c"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        fsx: true

iam:
  withOIDC: true
