apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
    - name: inference
      port: 5543
      targetPort: 5543
    - name: monitoring
      port: 6100
  clusterIP: 10.101.156.112
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis
  labels:
    app: sentiment-analysis
spec:
  selector:
    matchLabels:
      app: sentiment-analysis
  replicas: 2
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
        - name: sentiment-analysis
          image: sentiment_analysis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: inference
              containerPort: 5543
            - name: monitoring
              containerPort: 6100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-analysis-monitor
  labels:
    app: sentiment-analysis
spec:
  selector:
    matchLabels:
      app: sentiment-analysis
  endpoints:
    - interval: 5s
      port: monitoring
