# Reference: https://eksctl.io/usage/eksctl-karpenter/

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks-karpenter
  version: "1.25"
  region: us-west-2
  tags:
    karpenter.sh/discovery: do-eks-karpenter

iam:
  withOIDC: true

karpenter:
  version: 'v0.27.0'
  createServiceAccount: true
  defaultInstanceProfile: 'KarpenterNodeInstanceProfile'

managedNodeGroups:
  - name: c5-xl-do-eks-karpenter-ng
    instanceType: c5.xlarge
    instancePrefix: c5-xl
    privateNetworking: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 300
    iam:
      withAddonPolicies:
        cloudWatch: true

