apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-hpc
  version: "1.21"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: true

managedNodeGroups:
  - name: c5n-18xl
    instanceType: c5n.18xlarge
    instancePrefix: c5n-18xl
    privateNetworking: true
    availabilityZones: ["us-east-1a"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
