apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks
  version: "1.24"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.9.1-eksbuild.1

managedNodeGroups:
  - name: p4d-24xlarge-efa
    instanceType: p4d.24xlarge
    instancePrefix: p4d-efa
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: p3dn-24xlarge-efa
    instanceType: p3dn.24xlarge
    instancePrefix: p3dn-efa
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: g4dn-metal-efa
    instanceType: g4dn.metal
    instancePrefix: g4dn-efa
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
  - name: p3-8xlarge
    instanceType: p3.8xlarge
    instancePrefix: p3-8xl
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    minSize: 0
    desiredCapacity: 1
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
  - name: p3-16xlarge
    instanceType: p3.16xlarge
    instancePrefix: p3-16xl
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        efs: true
        fsx: true
        cloudWatch: true
