endpoints:
    - task: "import:custom_qa_pipeline"
      route: /invocations
      model: zoo:nlp/question_answering/distilbert-none/pytorch/huggingface/squad/pruned80_quant-none-vnni
      batch_size: 1
