name: Test Checks

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  SPARSEZOO_TEST_MODE: true
  NM_DISABLE_ANALYTICS: "true"

jobs:
  base-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: "⚙️ Install sparsezoo dependencies"
        run: pip install sparsezoo/
      - name: "Clean sparsezoo directory"
        run: rm -r sparsezoo/
      - name: ⚙️ Install dependencies
        run: pip install deepsparse-nightly[dev,server,image_classification,transformers,clip]==1.7.0.20231210
      - name: DeepSparse build info
        run: python -c "from deepsparse import generated_version; print(generated_version.splash)"
      - name: List installed dependencies
        run: pip freeze
      - name: List installed dependencies
        run: pip list
      - name: Run base tests
        run: make test
  cli-smoke-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.11']
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: "⚙️ Install sparsezoo dependencies"
        run: pip install sparsezoo/
      - name: "Clean sparsezoo directory"
        run: rm -r sparsezoo/
      - name: ⚙️ Install dependencies
        run: pip install .[dev,server,image_classification,transformers]
      - name: Run CLI smoke tests
        run: PYTEST_ARGS="-m smoke" make test TARGETS=cli,nobase
  integrations-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: "⚙️ Install sparsezoo dependencies"
        run: pip install sparsezoo/
      - name: "Clean sparsezoo directory"
        run: rm -r sparsezoo/
      - name: ⚙️ Install dependencies
        run: pip install .[dev,haystack]
      - name: Run integrations tests
        run: make test_integrations
