num_cores: 16
num_concurrent_batches: 8
endpoints:
  - name: main qa static model
    endpoint: /predict/static
    task: question-answering
    model: zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/12layer_pruned80_quant-none-vnni
    batch_size: 1
    accept_multiples_of_batch_size: False
    bucketing:
      sequence_lengths: [10, 128]